name: Update Terminal GIF

on:
  schedule:
    - cron: '0 0 * * *' # Updates every 24 hours at midnight
  workflow_dispatch: # Allows you to test it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade github-readme-terminal

      - name: Generate GIF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p frames
          python shrey_os_perfect_fit.py
          ffmpeg -y -r 15 -i frames/frame_%d.png -filter_complex "[0:v] split [a][b];[a] palettegen [p];[b][p] paletteuse" output.gif

      - name: Save to Repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.gif
          git commit -m "Daily terminal update" || exit 0
          git push
